# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8597a35b0b89082835833f38fadb0307d75736b17511b062f2f5de0f285255cbe6d6691f0ce5d92557f6cc1f9fc057c668c3962800d7c3dfb7b966e1d9509764

test:
  secret_key_base: 7a13871d8ab91dda1ed15e2ed901ee18a17a117fff2488ee0f92bc149ee94116ea3f23c75de8e7054ace2f134b0597cd00e7128f24d52126708f25a97c314790

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
